Sistema.WebApp/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace Sistema.WebApp.Controllers
{

    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Sistema.WebApp/Controllers/UsuarioController.cs
using AutoMapper;
using Sistema.WebApp.Models.ViewModels;
using Sistema.WebApp.Models;
using Sistema.WebApp.Utilidades.Response;
using Sistema.Negocio.Interfaces;
using Sistema.Entidades.Administracion;
using Microsoft.AspNetCore.Mvc;

namespace Sistema.WebApp.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IRolNRepository _rolNRepository;
        private readonly IUsuarioNRepository _usuarioNRepository;
        private readonly IMapper _mapper;

        public UsuarioController(IRolNRepository rolNRepository, IUsuarioNRepository usuarioNRepository, IMapper mapper)
        {
            _rolNRepository = rolNRepository;
            _usuarioNRepository = usuarioNRepository;
            _mapper = mapper;
        }

        public IActionResult Index()
        {

            var lst = _usuarioNRepository.Listar(true);

            IEnumerable<Usuario> lstVM = _mapper.Map<IEnumerable<Usuario>>(lst.Result);

            return View(lstVM);
        }
    }
}

Sistema.WebApp/Controllers/VentaController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Sistema.Entidades.Inventario;
using Sistema.Entidades.Ventas;
using Sistema.Negocio.Interfaces;
using Sistema.WebApp.Models;
using Sistema.WebApp.Models.ViewModels;
using Sistema.WebApp.Utilidades.Response;
using System.Transactions;

namespace Sistema.WebApp.Controllers
{
    public class VentaController : Controller
    {
        private readonly IVentaNRepository _ventaNRepository;
        private readonly IProductoNRepository _productoNRepository;
        private readonly ICategoriaProductoNRepository _categoriaProductoNRepository;                
        private readonly IMapper _mapper;

        public VentaController(IVentaNRepository ventaNRepository, IProductoNRepository productoNRepository, ICategoriaProductoNRepository categoriaProductoNRepository, IMapper mapper)
        {
            _ventaNRepository = ventaNRepository;
            _productoNRepository = productoNRepository;
            _categoriaProductoNRepository = categoriaProductoNRepository;
            _mapper = mapper;
        }

        public IActionResult Index()
        {

            var lstProducts = _productoNRepository.ListarAsync();
            IEnumerable<ProductoVM> listProductsVM = _mapper.Map<List<ProductoVM>>(lstProducts.Result);

            // Generar items de productos
            if (listProductsVM != null)
            {
                listProductsVM = listProductsVM.Select(i => { i.Descripcion = $"{i.Descripcion} - [Precio: {i.Precio}]"; return i; }).ToList();
            }
            ViewBag.listProducts = listProductsVM;

            return View();
        }

        [HttpPost]
        public IActionResult Registrar([FromBody] AgregarVentaVM model)
        {
            GenericResponse<string> genericResponse = new GenericResponse<string>();

            try
            {                

                // Se valida que la compra tenga un detalle
                if (model.DetalleVentaModels == null || model.DetalleVentaModels.Count() < 1)
                {
                    genericResponse.Mensaje = "La venta no tiene detalle, Favor Validar..!";
                    genericResponse.Estado = false;
                    genericResponse.EstadoCode = StatusCodes.Status400BadRequest.ToString();

                    return StatusCode(StatusCodes.Status200OK, new { data = genericResponse });
                }

                using (TransactionScope scope = new TransactionScope())
                {                    

                    MaestroVentaModel maestroVenta = new()
                    {
                        Numero = model.Numero,
                        NombreCliente = model.NombreCliente,
                        SubTotal = model.Subtotal,
                        Total = model.Total,
                        FechaCreacion = DateTime.Now                        
                    };

                    var compraReg = _ventaNRepository.AgregarAsync(_mapper.Map<MaestroVenta>(maestroVenta)).Result;

                    // Validar si se obtuvo el ID del maestro de compra
                    if (compraReg == null || compraReg.Id < 1)
                    {
                        genericResponse.Mensaje = "No fue posible guardar el encabezado de la venta..!";
                        genericResponse.Estado = false;
                        genericResponse.EstadoCode = StatusCodes.Status204NoContent.ToString();

                        scope.Dispose();

                        return StatusCode(StatusCodes.Status200OK, new { data = genericResponse });
                    }

                    // Guardar detalle de la compra
                    foreach (var item in model.DetalleVentaModels)
                    {

                        DetalleVentaModel detalleVenta = new()
                        {
                            VentaId = compraReg.Id,
                            ProductoId = item.ProductoId,
                            Cantidad = item.Cantidad,
                            Total = item.Total,
                            Precio = item.Precio
                        };

                        var detallecompraReg = _ventaNRepository.AgregarDetalleAsync(_mapper.Map<DetalleVenta>(detalleVenta)).Result;

                        // Validar si se obtuvo el ID del maestro de compra
                        if (detallecompraReg == null || detallecompraReg.Id < 1)
                        {
                            genericResponse.Mensaje = "No fue posible guardar el encabezado de la venta..!";
                            genericResponse.Estado = false;
                            genericResponse.EstadoCode = StatusCodes.Status204NoContent.ToString();

                            scope.Dispose();

                            return StatusCode(StatusCodes.Status200OK, new { data = genericResponse });
                        }
                    }                    

                    // Finalizar transacción
                    scope.Complete();
                }

            }
            catch (TransactionAbortedException ex)
            {
                genericResponse.EstadoCode = StatusCodes.Status500InternalServerError.ToString();
                genericResponse.Estado = false;
                genericResponse.Mensaje = "Error Interno: [Fallo en Transacción] - Favor Validar..!";
            }
            catch (Exception ex)
            {
                var exMessage = ex.Message;

                if (exMessage.Contains("Tarea Cancelada: "))
                {
                    genericResponse.EstadoCode = StatusCodes.Status500InternalServerError.ToString();
                    genericResponse.Estado = false;
                    genericResponse.Mensaje = "Información: " + ((ex.InnerException != null) ? ex.InnerException.Message : exMessage);

                    return StatusCode(StatusCodes.Status200OK, new { data = genericResponse });
                }

                genericResponse.EstadoCode = StatusCodes.Status500InternalServerError.ToString();
                genericResponse.Estado = false;
                genericResponse.Mensaje = "Error Interno Favor Validar..!";

            }

            return StatusCode(StatusCodes.Status200OK, new { data = genericResponse });
        }

    }
}

Sistema.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sistema Venta</title>

    <!-- Custom fonts for this template-->
    @*<link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">*@

    <link href="~/lib/fontawesome/css/all.min.css" rel="stylesheet" type="text/css" />

    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <link href="~/lib/datatables/datatables.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/DataTables-1.12.1/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/Responsive-2.3.0/css/responsive.dataTables.min.css" rel="stylesheet" />
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
    <link href="~/lib/jquery-ui-1.13.2/jquery-ui.min.css" rel="stylesheet" />

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.css" rel="stylesheet">

    @*
    <link href="~/vendor/toastr/toastr.min.css" rel="stylesheet">
    <link href="~/vendor/sweetalert/sweetalert.css" rel="stylesheet">
    *@

    @await RenderSectionAsync("Style", required:false)
</head>
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon">
                    <i class="fas fa-desktop"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Sistema Ventas</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Dashboard")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Nav Item - Administración Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAdministracion">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Administración</span>
                </a>
                <div id="collapseAdministracion" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index", "Usuario")">Usuarios</a>
                        <a class="collapse-item" href="negocio.html">Negocio</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Inventario Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseInventario">
                    <i class="fas fa-fw fa-clipboard-list"></i>
                    <span>Inventario</span>
                </a>
                <div id="collapseInventario" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="categorias.html">Categorias</a>
                        <a class="collapse-item" href="productos.html">Productos</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Venta Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseVenta">
                    <i class="fas fa-fw fa-tags"></i>
                    <span>Ventas</span>
                </a>
                <div id="collapseVenta" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index","Venta")">Nueva Venta</a>
                        <a class="collapse-item" href="historial_venta.html">Historial Venta</a>
                    </div>
                </div>
            </li>
            
            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                <img class="img-profile rounded-circle"
                                     src="https://images.unsplash.com/photo-1519648023493-d82b5f8d7b8a?w=300">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="perfil.html">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Perfil
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Salir
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        &copy; @DateTime.Now.Year <strong> - José Andrés Guevara Méndez</strong>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Modal Principal -->
    <div id="modalPrincipalPopup" class="modal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 id="modalPrincipalTitle" class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div id="modalPrincipalBody" class="modal-body">
                    <div class="card shadow-sm  my-2">
                        <div class="card-body p-3">
                            <h6 class="card-title font-weight-bold text-primary">Información</h6>
                            <hr class="mt-1 mb-1" />
                            <div class="form-row">
                                <div class="col-12">
                                    <div id="content-modalPrincipalBody" class="col-md-12 col-sm-* col-xs-*">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal Extra Largo -->
    <div id="modalPrincipalPopupExtralarge" class="modal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-xl" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 id="modalPrincipalTitle" class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div id="modalPrincipalBodyExtralarge" class="modal-body">
                    <div class="card shadow-sm  my-2">
                        <div class="card-body p-3">
                            <h6 class="card-title font-weight-bold text-primary">Información</h6>
                            <hr class="mt-1 mb-1" />
                            <div class="form-row">
                                <div class="col-12">
                                    <div id="content-modalPrincipalBodyExtralarge" class="col-md-12 col-sm-* col-xs-*">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>   

    @* Modal para mostrar loading *@
    <div id="modalMainLoading" class="modal" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-loading" role="document">
            <div id="modalMainLoadingBody" class="modal-body">
                <img class="img-responsive img-rounded transparent" style="width:90px !important; height:80px !important;" src="~/img/ZKZg.gif" />
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- jquery Unobtrusive Ajax -->
    <script src="~/lib/jquery/jquery.unobtrusive-ajax.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.js"></script>
    
    <!-- Sweet Alert 2 -->
    <script src="~/lib/sweetalert2/sweetalert2.all.min.js"></script>

    <!-- Sweet Alert -->
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    <script src="~/lib/sweetalert/custommessages.js"></script>

    <!-- Data Table -->
    <script src="~/lib/datatables/datatables.min.js"></script>
    <script src="~/lib/datatables/datatables-1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/responsive-2.3.0/js/dataTables.responsive.min.js"></script>

    <!-- Select2 -->
    <script src="~/lib/select2/js/select2.min.js"></script>

    <!-- JQuery -->
    <script src="~/lib/jquery-ui-1.13.2/jquery-ui.min.js"></script>

    <!-- ChartJS -->
    @*<script src="~/vendor/chart.js/Chart.min.js"></script>*@

    <script type="text/javascript">

        function showMainLoading() {
            $('#modalMainLoading').modal('show');
        }

        function modalCloseMainLoading() {
            $("#modalMainLoading").modal('hide');
        }
        
        function modalPrincipalOpen() {
            $("#modalPrincipalPopup").modal('show');
        }

        function modalPrincipalClose() {
            $("#modalPrincipalPopup").modal('hide');
        }

        function modalPrincipalExtraLOpen() {
            $("#modalPrincipalPopupExtralarge").modal('show');
        }

        function modalPrincipalExtraLClose() {
            $("#modalPrincipalPopupExtralarge").modal('hide');
        }

    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>